### ISSUE TITLE
BO Teil der SW Verteilung?

### ISSUE THREAD

**Issue by meschnigm** [ac-caterva/webserver-public#5]
Habe das bei mir getestet und es schaut gut aus. recht elegant mit dem link von "alt" nach "neu"

Soll mit der Verteilung die BO V10 und V20 verteilt werden?
Bisher hatte ich verstanden soll nur V10 verteilt werden.

**Comment by ac-caterva** [comment]
Nein, das waere eine Verteilung zur Caterva. Das ist der naechste Schritt ueber den ich mir Gedanken machen werde.

Lassen wir das Issue offen, ich werde dann hier meine Ideen aufschreiben.

**Comment by ac-caterva** [comment]
Ich habe die Verteilung auf die Caterva analog zur Verteilung auf die Pi implementiert. Folgende Dateien werden auf die Caterva kopiert:
-  BC_Check.sh
- uli_Abfrage_Status.sh
- uli_invoice_Wirkungsgrad_online.sh
- uli_invoice_aktuell_online.sh 

Doku: [Readme.md im webserver-public](https://github.com/ac-caterva/webserver-public/blob/main/README.md)
