### ISSUE TITLE
Seit Update auf den webserver-public läuft die Websiten Oberfläche nicht mehr/kaum mehr

### ISSUE THREAD

**Issue by schicho** [ac-caterva/webserver-public#6]
Hallo, ich muss mich vielleicht erstmal vorstellen. Ich bin der Basti, Sohn von der Elisabeth SN94.

Ich poste hier, da ich selber keinen Zugriff auf den Discord Server habe. Sollte das Problem eher auf den Discord Server verlagert werden, dann bitte einfach sagen.

### Nun zum Problem:

Ich hab heute auf das den web-server public geupdatet, nachdem dieser ja nun automatisch updates durchführen soll. Das Problem ist, seither läuft die Weboberfläche nicht mehr.

Folgendes habe ich gemacht:

- Den update Prozess wie im Readme durchgeführt, dabei gab es keine Probleme. Keine Log Fehler.
- FHEM ging erstmal, aber stürzt scheinbar beim ersten minütlichen Sync mit den Daten des Business Controller (?) ab. Genauer: Zunächst läuft der Webserver noch, aber die angezeigten Daten sind noch von vor dem Update. Sobald der erste Sync kommt, entweder völlig automatisch, oder(?) sobald man versucht die Log Datei in der Weboberfläche anzuschauen, lädt es nurnoch ewig.
- Man bekommt keine Meldung über "unreachable" oder "timeouts", die Ladezeiten sind nur ewig. z.B. nur der Wechsel von der Wertetabelle zu den Graphen dauert 2 Minuten. Anschließend funktioniert die Weboberfläche wieder für eine Minute, bis das nächste Update der Daten es wieder verlangsamt.
- Auffällig war auch das der Graph zur Auslasstung des Business Controller viel höher ist seit dem Update. Etwa um 1.5 Punkte mehr. Liegt es daran, oder ist das jetzt einfach durch das update so?

- Ich habe gemerkt, dass der "alte" webserver nicht wie im readme steht durch den update prozess gelöscht worden ist. Der Ordner samt Dateien war nach dem update noch immer vorhanden. Dachte es gibt vielleicht deswegen einen Konflikt und habe den Ordner gelöscht. Problem besteht noch immer.
- Habe FHEM über die Weboberfläche geupdatet. Update lief problemlos durch, allerdings besteht das Problem auch trotzdem noch
- Durch neustarten der Pi, kann ich den Webserver neustarten und ihn für etwa eine Minute wieder bedienen. Dabei fällt auf, das Timestamps von den vorherigen Anläufen nicht übernommen werden. Anscheinend wird garnichts gespeichert?

So das war jetzt sehr viel Information, aber ich hoffe da ist alles dabei was ich gemacht und gemerkt habe.
Ich bin ab morgen Mittag wieder weg zurück an die Uni und kann weitere Informationen entweder noch morgen Vormittag oder dann wieder ab nächsten WE zur Verfügung stellen.

Ich denke die caterva log wäre sicherlich von Vorteil, allerdings kann ich die nicht über die Weboberfläche anzeigen lassen, wie beschrieben. Wenn du mir aber erklären kannst, wo die Log auf der Pi gespeichert ist, dann kann ich die direkt von dort kopieren und hier als Anhang reinschicken.

Vielen Dank und Liebe Grüße

Basti

**Comment by quinsifh** [comment]
Als ich mal ähnliche Probleme hatte, lag das an Prozessen der Caterva. Deswegen reboot der Caterva oder mal aus und ein schalten.

**Comment by schicho** [comment]
Danke für die schnelle Hilfe. Wie mach ich das am besten?

sudo reboot über SSH hat bei mir einfach nicht funktioniert. (Keine Reaktion des BC)
Und reboot in FHEM hat nur die Weboberfläche crashen lassen und es ist nichts geschehen.

Ist FI rein und raus meine letzte Möglichkeit? Hab mich davor bisher noch gesträubt.

**Comment by quinsifh** [comment]
Damit ist das die einzige Möglichkeit, ist aber nicht so schlimm..  vor dem einschalten 1min warten

**Comment by schicho** [comment]
Das scheint es behoben zu haben. Läuft wieder!

Vielen Dank :)

Off topic:
In der Log befinden sich noch folgende Warnungen. Die hatte ich aber auch schon vor dem heutigen Update iirc:

> 2021.04.18 22:57:51 1: /home/admin/bin/BusinessOptimum.sh does not exist
2021.04.18 22:58:07 1: response: 2

>2021.04.18 22:58:07 1: /tmp/BusinessOptimumActive does not exist
2021.04.18 22:58:28 1: response: 2

>2021.04.18 22:58:28 1: /tmp/ForcedChargingActive does not exist
2021.04.18 22:58:48 1: response: 2

>2021.04.18 22:58:48 1: /tmp/ModuleBalancingActive does not exist
2021.04.18 22:59:14 1: response: 2

>2021.04.18 22:59:14 1: /tmp/CellBalancingActive does not exist
2021.04.18 22:59:14 3: define at_Sec_Counter at +00:00:03 set BusinessOptimum_Befehle . : at_Sec_Counter already defined, delete it first

Ist das in Ordnung so oder sollte da noch was gemacht werden?

**Comment by meschnigm** [comment]
Falls das Problem nicht behoben ist kann ich mir das am Samstag Vormittag ansehen.
Gruß Manuel SN068

**Comment by meschnigm** [comment]
Sorry sehe erst jetzt die gesamte Korrespondenz- Die Meldungen sind so zu erwarten - kein Problem....
